### ISSUE TITLE
Clearer error

### ISSUE THREAD

**Issue by kosukesando** [JakeGrainger/WhittleLikelihoodInference.jl#11]
Hi, thanks for the great package!
I got an error for essentially using an incorrect model (JONSWAP) for HNE data, which is mistake on my part for not reading the manual.

However, I thought the error message [here](https://github.com/JakeGrainger/WhittleLikelihoodInference.jl/blob/5c627b8507da04160c3c7967dae37394e9ae2c58/src/fit.jl#L25) could be made clearer to say

`ArgumentError: Dimension of the TimeSeries($(size(ts,2))) does not match the dimension of the TimeSeriesModel($(ndims(model))).`

I probably could've just made an PR at this point but oh well.

**Comment by JakeGrainger** [comment]
Hi, I'm glad its useful

Thank you for the suggestion, I have updated the error message as you suggested, that is nicer
